- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io
    become : yes
    become_user : root

  - name : Start Docker Service
    command : sudo systemctl start docker
    become : yes
    become_user : root

- name: Running Kubernetes Cluster
  hosts: localhost
  become: true
  tasks:
    - name: Clone the Healthcare Project Repository
      git:
        repo: "https://github.com/Balunideepak/healthcare-project.git"
        dest: "/tmp/healthcare-project"
        clone: yes
        update: yes

    - name: Apply Kubernetes manifests
      command: kubectl apply -f /tmp/healthcare-project/deployment.yaml
      register: k8s_output

    - name: Display kubectl apply output
      debug:
        var: k8s_output.stdout_lines
