- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Updating apt
      command: sudo apt-get update

    - name: Clone the GitHub repository
      git:
        repo: "https://github.com/Balunideepak/Deployment-script.git"
        dest: "/tmp/Deployment-script"
        clone: yes
        update: yes
        force: yes

    - name: Changing permission to run script
      command: sudo chmod 700 /tmp/Deployment-script/docker.sh
      become: yes
      become_user: root

    - name: Running Docker script to install Docker
      command: /tmp/Deployment-script/docker.sh
      become: yes

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes

- name: Running Kubernetes Cluster
  hosts: localhost
  become: true
  tasks:
    - name: Clone the Healthcare Project Repository
      git:
        repo: "https://github.com/Balunideepak/healthcare-project.git"
        dest: "/tmp/healthcare-project"
        clone: yes
        update: yes

    - name: Apply Kubernetes manifests
      command: kubectl apply -f /tmp/healthcare-project/deployment.yaml
      register: k8s_output

    - name: Display kubectl apply output
      debug:
        var: k8s_output.stdout_lines
